name: Build EXE and Release (Windows)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller (onedir then onefile)
        run: |
          pyinstaller --exclude-module PyQt5 --noconfirm --onefile --windowed --name "CatAIDBViewer" --add-data "src\\ui;ui" src\app.py 

      - name: List dist directory
        run: |
          dir dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/CatAIDBViewer.exe
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}